base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    #path("user/", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("study/", include("study.urls")),
    path("", include("offers.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

offers/urls.py
from django.urls import path

from . import views
from dashboard.views import OfferUpdateView,OfferDeleteView,CompanyUpdateView,CompanyDeleteView

app_name = "offers"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path("companies/", views.CompaniesListView.as_view(), name="companies-list"),
    path("offer/<int:pk>/", views.OfferDetailView.as_view(), name="offer-detail"),
    path("company/<int:pk>/", views.CompanyDetailView.as_view(), name="company-detail"),
    path(
        "dashboard/offer/edit/<int:offer_id>/", OfferUpdateView.as_view(), name="edit-offer"
    ),
    path(
        "dashboard/offer/delete/<int:offer_id>/", OfferDeleteView.as_view(), name="delete-offer"
    ),
    path(
        "dashboard/offer/edit_company/<int:pk>/", CompanyUpdateView.as_view(), name="edit-company"
    ),
    path(
        "dashboard/offer/delete_company/<int:pk>/", CompanyDeleteView.as_view(), name="delete-company"
    ),
]

offers/forms.py
from dashboard.models import (
    Firma,
)
from django import forms


class DateSortingForm(forms.Form):

    CHOICES = (("1", "Date - Oldest"), ("2", "Date - Newest"))

    order_by = forms.ChoiceField(
        choices=CHOICES,
        required=False,
    )


class SearchForm(forms.Form):

    name = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["name"].required = False
        self.fields["name"].label = ""
        self.fields["name"].widget.attrs["placeholder"] = "Search by name"


class ApplyForm(forms.ModelForm):

    offer = forms.IntegerField(widget=forms.HiddenInput())

    class Meta:
        model = Firma
        fields = "__all__"

offers/views.py
from typing import Any, Dict

from dashboard.models import Posao,Firma
from django.db.models import QuerySet
from django.views.generic import ListView, DetailView
from django.forms import Textarea

from .forms import (
    DateSortingForm,
    SearchForm,
    
)

class HomePageView(ListView):

    model = Posao
    template_name = "home_page.html"
    paginate_by = 10

    def get_queryset(self) -> QuerySet[Any]:

        queryset = super().get_queryset()

        name = self.request.GET.get("name")
        if name:
            queryset = queryset.filter(naziv_posla__icontains=name)

        positions = self.request.GET.getlist("localization")
        if positions:
            queryset = queryset.filter(firma__in=positions)

        order_by2 = self.request.GET.get("order_by")

        if order_by2:
            if order_by2 == "1":
                queryset = queryset.order_by("datum_izrade")
            if order_by2 == "2":
                queryset = queryset.order_by("-datum_izrade")

 
        return queryset

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:

        context = super().get_context_data(**kwargs)
        context["date_sorting_form"] = DateSortingForm(self.request.GET)
        context["search_form"] = SearchForm(self.request.GET) 

        return context

class CompanyDetailView(DetailView):

    model = Firma
    template_name = "company_detail.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        
        context = super().get_context_data(**kwargs)
        context["object_list"] = Posao.objects.filter(firma=self.kwargs["pk"])
        return context

class OfferDetailView(DetailView):

    model = Posao
    template_name = "offer_detail.html"
    fields = [
        "naziv_posla",
        "opis_posla",
        "placa",
        "lokacija",
        "kontakt_osobe",
        "firma",
        "image",
    ]
    widgets = {
            'text': Textarea(attrs={'rows':5, 'cols':10}),
        }   
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class CompaniesListView(ListView):

    model = Firma
    paginate_by = 10
    template_name = "companies_list.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        return context

offers/templates/companies_list.html
{% extends 'base.html' %}

{% block meta_title%} Jobs portal | Companies list {% endblock %}

{% block content %}

{% if object_list %}
{% for object in object_list %}
<div class="container">
      <div class="card mb-5 mt-5" style="max-width: 1400px;">
          <div class="row g-0">
            <div class="col-md-4">
              {% if object.image %}
              <a href="{% url 'offers:company-detail' object.id %}">
              <img style="width: 250px; height: 120px; object-fit: contain;" class="mx-auto d-block pt-3 pb-3" src="http://127.0.0.1:8000/media/{{object.image}}"  alt={{object.name}}></a>
              {% else %}
              <a href="{% url 'offers:company-detail' object.id %}">
              <img style="width: 250px; height: 120px; object-fit: contain;" class="mx-auto d-block pt-3 pb-3" src="https://www.allianceplast.com/wp-content/uploads/no-image-1024x1024.png"  alt="no image" /></a>
              {% endif %}
            </div>
            <div class="col-md-8">
              <div class="card-body">
              <div class="d-flex justify-content-between">
                <a style="text-decoration: none; color: black;" href="{% url 'offers:company-detail' object.id %}"><h2 class="card-title">{{object.naziv_firme}}</h2></a>
              </div>
                {% if object.opis %}
                <div class="d-flex justify-content-between">
                  <p class="card-text"><small class="text-body-secondary">{{object.opis}}</small></p>
                </div>
                {% else %}
                {% endif %}
              </div>
            </div>
          </div>
        </div>
  </div>
{% endfor %}
{% else %}
<div class="container" style="height: 600px">
    <h2 class="text-center">There is no any resources yet</h2>
</div>
{% endif %}


{% include "pagination.html" %}

{% endblock %}

offers/templates/company_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block meta_title%} Jobs portal | {{object.username}} {% endblock %}

{% block content %}

<div class="container mt-5 mb-5">
  <h2 style="font-size: 40px; font-weight: 600">{{object.naziv_firme}}</h2>
  <div class="row">
            
    <div class="col-auto mr-auto">
        <a href="{% url 'offers:edit-company' object.id %}" class="btn btn-primary" role="button">Edit</a>
    </div>
    <div class="col-auto mr-auto">
        <form method="POST" action="{% url 'offers:delete-company' object.id %}">
            {% csrf_token %}
            <input method="POST" type="submit" class="btn btn-danger" role="button" value="Delete">
        </form>
    </div>
</div> 

    {{object.opis}}


{% if object_list %}
<div class="container">
  <h2 class="mt-5">Companies offers</h2>
    {% for object in object_list %}
        <div class="card mb-5 mt-5" style="max-width: 1400px;">
            <div class="row g-0">
              <div class="col-md-4">
                {% if object.image %}
                <img style="width: 250px; height: 120px; object-fit: contain;" src="http://127.0.0.1:8000/media/{{object.image}}" class="mx-auto d-block pt-3 pb-3" alt={{object.company.name}}>
                {% else %}
                <img style="width: 250px; height: 120px; object-fit: contain;" src="https://www.allianceplast.com/wp-content/uploads/no-image-1024x1024.png" class="mx-auto d-block pt-3 pb-3" alt="no image" />
                {% endif %}
              </div>
              <div class="col-md-8">
                <div class="card-body">
                <div class="d-flex justify-content-between">
                  <a href="/offer/{{object.id}}"><h2 class="card-title">{{object.naziv_posla}}</h2></a>
                  <h5 class="card-title" style="color: green; font-weight: 800">{{object.placa}} Eur</h5>
                </div>
                  <div class="d-flex justify-content-between">
                    <p style="margin-right:10px" class="card-text"><small class="text-body-secondary">{{object.naziv_firme}}</small></p>
                    <p style="margin-right:10px" class="card-text"><small class="text-body-secondary">{{object.datum_izrade}}</small></p>
                    <p style="margin-right:10px" class="card-text"><small class="text-body-secondary">{{object.lokacija}}</small></p>
                    {% if object.return_requirements %}
                        <p style="margin-right:10px" class="card-text"><small class="text-body-secondary">{{object.return_requirements}}</small></p>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
    {% endfor %}
    </div>
{% else %}
<div class="container">
  <h2 class="mt-5">This company doesn't have any new offers</h2>
</div>
{% endif %}


</div>
{% endblock %}

offers/templates/home_page.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block meta_title%} Jobs portal | Home page {% endblock %}

{% block content %}


  <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="offcanvasExampleLabel">Filter offers</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
    <form method="get" action=".">
        {{firm_form|crispy}}
        {{date_sorting_form|crispy}}
        <button class="btn btn-primary" type="submit">Search</button>
    </form>
    </div>
  </div>



<div class="container mt-5">
    <form method="get" action=".">
        <div class="row">
            <div class="col">
                {{search_form|crispy}}
            </div>
            <div class="col">
                <button class="btn btn-primary float-right" type="submit">Search</button>
            </div>
        </div>
        <div class="row">
            <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
                More filters</button>
        </div>
    </form>
</div>

{% if object_list %}
<div class="container">
{% for object in object_list %}
    <div class="card mb-5 mt-5" style="max-width: 1400px;">
        <div class="row g-0">
          <div class="col-md-4">
            {% if object.image %}
            <a href="/offer/{{object.id}}">
            <img style="width: 250px; height: 120px; object-fit: contain;" class="mx-auto d-block pt-3 pb-3" src="http://127.0.0.1:8000/media/{{object.image}}"  alt={{object.company.name}}></a>
            {% else %}
            <a href="/offer/{{object.id}}">
            <img style="width: 250px; height: 120px; object-fit: contain" class="mx-auto d-block pt-3 pb-3" src="https://www.allianceplast.com/wp-content/uploads/no-image-1024x1024.png" alt="no image" /></a>
            {% endif %}
          </div>
          <div class="col-md-8">
            <div class="card-body">
            <div class="d-flex justify-content-between">
              <a style="text-decoration: none; color: black;" href="/offer/{{object.id}}"><h2 class="card-title">{{object.naziv_posla}}</h2></a>
              <h5 class="card-title" style="color: green; font-weight: 800">{{object.placa}} Eur</h5>
            </div>
              <div class="d-flex justify-content-between">
                <a style="margin-right: 10px" href="company/{{object.firma.id}}"> <p class="card-text"><small class="text-body-secondary">{{object.firma}}</small></p> </a>
                <p style="margin-right: 10px" class="card-text"><small class="text-body-secondary">{{object.datum_izrade}}</small></p>
                <p style="margin-right: 10px" class="card-text"><small class="text-body-secondary">{{object.lokacija}}</small></p>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endfor %}
</div>
{% else %}

<div class="container" style="height: 600px">
    <h2 class="text-center">There is no offers &#128531;</h2>
</div>
{% endif %}


{% include "pagination.html" %}
{% endblock %}

offers/templates/offer_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block meta_title%} Jobs portal | {{object.name}} {% endblock %}

{% block content %}
<link rel="stylesheet" href="linedot.css">
<div class="container mt-5">
    <h2>{{object.naziv_posla}} |
        {{object.placa}} Eur<br>
        <div class="row">
            
            <div class="col-auto mr-auto">
                <a href="{% url 'offers:edit-offer' object.id %}" class="btn btn-primary" role="button">Edit</a>
            </div>
            <div class="col-auto mr-auto">
                <form method="POST" action="{% url 'offers:delete-offer' object.id %}">
                    {% csrf_token %}
                    <input method="POST" type="submit" class="btn btn-danger" role="button" value="Delete">
                </form>
            </div>
        </div>  
    </h2>
    {{object.datum_izrade}} <br>
    <strong>Firma: </strong>{{object.firma}} <br><br>
    <blockquote class="blockquote">
        <p>{{object.opis_posla|linebreaksbr}}</p>
    </blockquote>
    <h3><strong>Lokacija: </strong></h3>
    <p class="h4">{{object.lokacija}} </p><br>
    <h3><strong>Kontakt Firme: </strong></h3><p class="h4">{{object.kontakt_osobe}} </p> <br>
    <h3><strong>Plaća: </strong></h3><p class="h4">{{object.placa}} Eur</p><br>
</div>


{% endblock %}